name: Build + Deploy

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

jobs:
  deploy:
    name: Build, test and deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 
        - 14.x

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Clean install
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Deploy
        env:
          USERNAME: ${{ secrets.USERNAME }}
          USEREMAIL: ${{ secrets.USEREMAIL }}
        run: |
          git config --global user.email $USEREMAIL
          git config --global user.name $USEREMAIL
          npm run deploy