name: Build + Deploy

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 
        - 14.x

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
        - 14.x

    steps:
     - run: npm test

  deploy:
    name: Deploy
    needs: [build, test]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
        - 14.x

    steps:
     - run: npm run deploy