name: Build + Deploy

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

jobs:
  deploy:
    name: Build, test and deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 
        - 14.x

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build
      - run: npm test
      - run: npm run deploy