name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build and deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install and build
    uses: actions/setup-node@v1
    - run:  npm ci
    - run: npm run build
    - run: npm run build:tailwind

    - name: Test
    uses: actions/setup-node@v1
    - run: npm test
    
    - name: Deploy
    uses: actions/setup-node@v1
    - run: npm run deploy
